### ISSUE TITLE
Compatibility with devices

### ISSUE THREAD

**Issue by Rishit30G** [Rishit30G/Personal-Portfolio#10]
There might be an issue related to compatibilities like Type JS text moving to the next line or the image looking too big on the normal phone screen

Fix Hint - Checkout `max-width` in CSS

**Comment by tusharkandpal** [comment]
Can I work on this ??

**Comment by rohitdubey1352** [comment]
Hello, @Rishit30G  have a look at my pull request, I have fixed the navbar and footer(Blur in the background), add new features in the card, added animations, and added a bottom to top button with JavaScript.
If u like my work then please, give me PR : )

**Comment by rohitdubey1352** [comment]
@Rishit30G  I'm really sorry but, it's not my fault, because before sending the files I checked all codes and also the files.
It's server issues and please remove the spam tag I am not doing any spam, if I did some mistake that's not the meaning is I m spamming to anyone.
