### ISSUE TITLE
Convert intro video to GIF

### ISSUE THREAD

**Issue by omrsfylmz** [Rishit30G/Personal-Portfolio#29]
Using intro video is not the usual case most of the time we use special GIFs, I can edit the readme file for this,

**Comment by Rishit30G** [comment]
Hey! 
Sorry for the delay, Please go ahead and make the GIF for the website on desktop. 
Also I would request that you make GIF for this website on an iPhone emulator also that would be great!

**Comment by Rishit30G** [comment]
@omrsfylmz Are you working on this ?
